
INSERT INTO `quizible`.`categories` (`name`, `createdAt`, `updatedAt`) VALUES ('Animals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`categories` (`name`, `createdAt`, `updatedAt`) VALUES ('Nature', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`categories` (`name`, `createdAt`, `updatedAt`) VALUES ('History', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`categories` (`name`, `createdAt`, `updatedAt`) VALUES ('Geography', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`categories` (`name`, `createdAt`, `updatedAt`) VALUES ('Cities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('What is the most important cat´s name?', '2', 'Tiger', 'Boris', 'Vaska', 'Murzik', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('What is the most important gog´s name?', '2', 'Wolf', 'Tuzik', 'Zuzik', 'Reks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('What is the most important bird´s name?', '2', 'Lastochka', 'Skvorec', 'Snigir', 'Sokol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('What is the most important fish´s name?', '2', 'Losos', 'Forel', 'Kit', 'Akula', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('What is the most important snake´s name?', '2', 'Piton', 'Kobra', 'Uzh', 'Anakonda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');


INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many trees there are?', '1', '1 M', '2 B', '2 M', '100 K', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many rivers there are?', '3', '5', '100', '200', '300', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many mountains there are?', '2', '100', '20', '2000', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many different arts of apples there are?', '4', '156', '222', '2000', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many different arts of cherrys there are?', '5', '105', '29', '223', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '2');


INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many years exist homosapiens?', '1', '1 M', '2020', '3012', '100 K', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How is name of first russian Zar?', '2', 'Petr', 'Anton', 'Dima', 'Nikolai', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('Who started second world war?', '3', 'Hitler', 'Elcin', 'Stalin', 'Lenin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many years ago lived Dinosaurs?', '4', '1 M', '2 B', '2 M', '100 K', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('In wich year was Corona virus activ?', '5', '2020', '1202', '2002', '200', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3');



INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many countries there are?', '1', '49', '202', '301', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '4');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('Which country is the biggest?', '2', 'russia', 'belarus', 'luxemburg', 'germany', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '4');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('Belongs Krym to russia?', '3', 'yes', 'no', 'maybe yes', 'maybe no', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '4');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('The smallest county of EU?', '4', 'Germany', 'Luxemburg', 'Poland', 'France', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '4');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('In Which continent is Mexico?', '5', 'North america', 'South america', 'Africa', 'Eurasia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '4');



INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many cities there are in germany?', '1', '49', '202', '27', '1002', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '5');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many cities there are in belarus?', '2', '149', '502', '45', '3100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '5');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many cities there are in russia?', '3', '490', '63', '74', '5100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '5');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many cities there are in france?', '4', '749', '51', '301', '35100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '5');
INSERT INTO `quizible`.`questions` (`question`, `complexity`, `answer1`, `answer2`, `answer3`, `answer4`, `createdAt`, `updatedAt`, `categoryId`) VALUES ('How many cities there are in japan?', '5', '4909', '26', '35', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '5');



INSERT INTO `quizible`.`users` (`name`, `city`, `street`, `plz`, `house`, `mail`, `password`, `strategy`, `createdAt`, `updatedAt`) VALUES ('adidas', 'berlin', 'lynarstreet', '13353', '5', 'adida@gmail.com', 'adidas', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`users` (`name`, `city`, `street`, `plz`, `house`, `mail`, `password`, `strategy`, `createdAt`, `updatedAt`) VALUES ('nike', 'minsk', 'minskstreet', '13553', '5', 'nike@gmail.com', 'nike', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`users` (`name`, `city`, `street`, `plz`, `house`, `mail`, `password`, `strategy`, `createdAt`, `updatedAt`) VALUES ('puma', 'hamburg', 'pumastreet', '23353', '5', 'puma@gmail.com', 'puma', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`users` (`name`, `city`, `street`, `plz`, `house`, `mail`, `password`, `strategy`, `createdAt`, `updatedAt`) VALUES ('reebok', 'munchen', 'reebokstreet', '53353', '5', 'reebok@gmail.com', 'reebok', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`users` (`name`, `city`, `street`, `plz`, `house`, `mail`, `password`, `strategy`, `createdAt`, `updatedAt`) VALUES ('umbro', 'berlin', 'umbrostreet', '13353', '5', 'umbro@gmail.com', 'umbro', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('1', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('1', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('1', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('1', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('2', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('2', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('2', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('2', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('2', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('3', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('3', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('3', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('4', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('4', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('4', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('5', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('5', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`user_categories` (`userId`, `categoryId`, `createdAt`, `updatedAt`) VALUES ('5', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWERTYI', '0', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQ2WERTYI', '0', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQ4WERTYI', '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQ5WERTYI', '0', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQ6WERTYI', '0', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER2TYI', '1', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER3TYI', '0', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER1TYI', '0', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER2TYIW', '1', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER4TYI', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER42TYI', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER452TYI', '1', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER45TYI', '0', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER4123TYI', '0', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('PQWER412TYI', '1', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO `quizible`.`quizzes` (`playerAge`, `playerPlz`, `userId`, `quizcodeId`, `createdAt`, `updatedAt`) VALUES ('20', '22010', '1', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizzes` (`playerAge`, `playerPlz`, `userId`, `quizcodeId`, `createdAt`, `updatedAt`) VALUES ('25', '21210', '1', '6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizzes` (`playerAge`, `playerPlz`, `userId`, `quizcodeId`, `createdAt`, `updatedAt`) VALUES ('36', '12310', '1', '9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizzes` (`playerAge`, `playerPlz`, `userId`, `quizcodeId`, `createdAt`, `updatedAt`) VALUES ('15', '53410', '1', '12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizzes` (`playerAge`, `playerPlz`, `userId`, `quizcodeId`, `createdAt`, `updatedAt`) VALUES ('10', '12310', '1', '15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);




INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('Tiger', '1', '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('2', '0', '1', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('3', '0', '1', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('4', '0', '1', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('1 M', '1', '2', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('6123', '0', '2', '6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('7123', '0', '2', '7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('8123', '0', '2', '8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('49', '1', '3', '9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('russia', '1', '3', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('yes', '1', '3', '11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('Germany', '1', '3', '12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('49', '1', '4', '13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('149', '1', '4', '14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('490', '1', '4', '15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('749', '1', '4', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('749', '1', '5', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('749', '1', '5', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('749', '1', '5', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`question_answers` (`answer`, `right`, `quizId`, `questionId`, `createdAt`, `updatedAt`) VALUES ('749', '1', '5', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('1', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('2', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('3', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('4', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('5', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('6', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('7', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('8', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('9', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('10', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('101', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('102', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('103', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('104', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('105', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('106', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('107', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('108', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('109', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('110', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('111', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('112', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('113', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('114', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('115', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('116', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('117', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('118', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('119', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('120', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('121', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('122', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('123', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('124', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('125', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('126', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('127', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('128', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('129', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('130', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('131', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('132', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('133', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('134', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('135', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('136', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('137', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('138', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('139', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('140', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('141', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('142', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('143', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('144', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('145', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('146', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('147', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('148', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('149', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('150', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('151', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('152', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('153', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('154', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('155', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('156', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('157', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('158', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('159', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('160', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('161', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('162', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('163', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('164', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('165', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('166', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('167', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('168', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('169', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('170', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('171', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('172', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('173', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('174', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('175', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('176', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('177', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('178', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('179', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('180', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('181', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('182', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('183', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('184', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('185', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('186', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('187', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('188', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('189', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('190', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('191', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('192', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('193', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('194', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('195', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('196', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('197', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('198', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('199', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('200', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('201', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('202', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('203', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('204', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('205', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('206', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('207', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('208', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('209', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('210', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('211', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('212', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('213', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('214', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('215', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('216', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('217', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('218', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('219', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('220', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('221', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('222', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('223', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('224', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('225', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('226', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('227', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('228', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('229', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('230', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('231', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('232', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('233', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('234', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('235', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('236', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('237', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('238', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('239', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('240', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('241', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('242', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('243', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('244', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('245', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('246', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('247', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('248', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('249', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('250', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('251', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('252', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('253', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('254', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('255', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('256', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('257', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('258', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('259', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('260', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('261', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('262', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('263', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('264', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('265', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('266', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('267', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('268', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('269', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('270', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('271', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('272', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('273', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('274', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('275', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('276', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('277', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('278', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('279', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('280', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('281', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('282', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('283', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('284', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('285', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('286', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('287', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('288', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('289', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('290', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('291', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('292', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('293', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('294', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('295', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('296', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('297', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('298', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('299', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('300', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-trwj', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-5hdm', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-96fb', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-ygso', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-u3tc', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-v4r7', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-h9ii', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-68q7', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-hjoh', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-g2py', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-nnk7', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-pa5n', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-k5td', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-eefm', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-my7d', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-e47o', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-2oe9', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-7eea', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-vnhu', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-8kvd', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-jz7y', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-jd4c', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-4yah', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-q7q4', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-5kd9', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-anq4', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-r6sc', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-cg6a', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-j5sz', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-y5ix', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-h8o2', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-83sb', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-6uzz', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-26mr', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-sehq', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-wfbo', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-f2ab', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-7qmu', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-75j3', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-b6po', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-8scq', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-p4no', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-kjgp', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-dan5', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-t4zw', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-kn47', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-jg6j', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-boj3', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-pr7m', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-b2e3', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-akx3', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-qv8f', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-xzqk', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-uw4d', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-9m7f', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-ghds', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-3tw5', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-xers', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-8btb', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-4bv8', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-or7u', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-y5wz', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-99yq', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-zvhf', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-5stu', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-44kz', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-v885', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-ibhx', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-u2kz', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-9gbh', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-fhq4', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-tfhb', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-qs2k', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-ay7r', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-2tbr', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-27h9', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-mkyw', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-4h9h', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-vq3a', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-gtjp', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-c383', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-prjs', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-yhxe', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-sa5q', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-9tky', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-wzc7', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-86dm', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-ku6p', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-39bm', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-yqty', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-tfcc', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-wsim', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-peez', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-9zys', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-yng5', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-93rd', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-kcn4', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-nwzr', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-7thj', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `quizible`.`quizcodes` (`code`, `played`, `userId`, `createdAt`, `updatedAt`) VALUES ('m-49ow', '0', '4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);